version: "3.9"

services:

  astar:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: astar_server
    labels:
      logging: "enabled"
      service: "itinerary-creator"
    environment:
      - ASTAR_LOG_LEVEL=INFO
    expose:
      - "50051"
    networks:
      - astar-net
      - hubert-network
    restart: on-failure

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: astar_envoy
    labels:
      logging: "enabled"
      service: "itinerary-creator-envoy"
    volumes:
      - ./observability/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "50051:50051"
      - "9901:9901"
    depends_on:
      - astar
    networks:
      - astar-net
      - hubert-network
    restart: on-failure

  unit_tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: astar_tests
    command: ["./unit_tests"]
    networks:
      - astar-net
    profiles:
      - test

networks:
  astar-net:
    external: true
    name: astar-net
  hubert-network:
    external: true
    name: hubert-network